[package]
name = "drbg"
version = "0.1.0"
edition = "2021"
description = """
Crypographic random number generator CTR_DRBG defined by NIST SP 800-90A r1.
"""
license = "MIT"
keywords = ["csprng","CTR_DRBG", "random", "rng"]
categories = ["algorithms", "cryptography"]

[dependencies]
aes = "0.8"
getrandom = { version = "0.2", features = ["std"]}

[dev-dependencies]
hex = "0.4"